application: your-application-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

instance_class: F1
automatic_scaling:
  min_idle_instances: 0

inbound_services:
- channel_presence
- warmup
- mail

handlers:
- url: /_ah/queue/deferred
  script: main.app
  login: admin

- url: /_ah/mail/.+
  script: main.app
  login: admin

- url: /static
  static_dir: static

- url: /mobiadmin/.*
  script: main.app
  secure: always
  login: admin

- url: /.*
  script: main.app
  secure: always
